openapi: 3.0.3
info:
  title: Flask API Template
  version: 0.1.0
  description: API endpoints for the Flask Template service. More in-depth documentation can be found <a href="https://google.com" target="_blank" rel="noopener noreferrer">here</a>.
  contact:
    name: Neel Roshania
    email: nroshania@gmail.com
servers:
  # - url: http://api.example.com/v1
  #   description: Main production server
  - url: http://localhost:8080
    description: Local development server
paths:
  /flasktemplate:
    get:
      description: General get requests.
      responses:
        '200':
          description: "good response"
components:
  responses:
    UnauthorizedError:
      description: API key is missing or invalid